### ISSUE TITLE
[수정] request가 중복되는 순차 호출 로직 api 병합 

### ISSUE THREAD

**Issue by dusdjhyeon** [Terraform-Canvas/back-end#10]
## 🚀 Feature Request

- [x] 기존 MergeEnvTf와 CreateTfvars를 하나의 api로 병합

## 📎 Additional context
- 기존의 두 api는 흐름상 순차적 호출이 필요 했었으므로 하나로 병합

**Comment by Eeap** [comment]
이거 수정되면 api docs 도 수정좀 해주세여 ㅎㅎ,,,
