### ISSUE TITLE
[수정] aws config 분리 및 버킷 생성 기능 추가

### ISSUE THREAD

**Issue by dusdjhyeon** [Terraform-Canvas/back-end#14]
## 🚀 Feature Request

- [x] aws config와 function 분리 
- [x] 버킷 생성 function 추가

## 📎 Additional context

- AWSConfig 내부호출

**Comment by Eeap** [comment]
이거 분리하는데 오래 걸리나여,.,.?

**Comment by Eeap** [comment]
aws 관련 sdk 추가해서 api로 반환해주는거 추가하려고 하는데 🥲

**Comment by dusdjhyeon** [comment]
아 jwt 본다고 까묵었다 지금 할게용
